#!/bin/bash
nodes=`sinfo --format="%N" --noheader`
header=true
pretty=true

print_usage () {
  cat << EOM
Usage: $0 [-n charles[01-19]]
    Get gpu usage for all, or specified nodes

Arguments:
    -n    (optional) specify nodes, either comma separated list, or summarised.
          Mirrors slurm command -n usage in sinfo, and -w usage for squeue." 
    -h    (optional) do not print header (only applies together with -p)
    -p    (optional) disable pretty printing and output raw CSV (pretty table is the default)

Output:
    Outputs three columns summarising the current usage of GPUs on the cluster:
        -- The 'in_use' column shows the number of GPUs that are currently allocated to a job.
        -- The 'usable' column shows the number of GPUs that are not in an error state or otherwise unable to be
            allocated to a job.
        -- The 'total' column shows the total number of GPUs, including those that are currently unable to be allocated
            to a job.

    The number of free GPUs (GPUs not allocated to a job and not in an error state) is the difference between the
    'usable' column and the 'in_use' column.

Examples:
    # Get status of all nodes aggregated (pretty table by default):
    $ ./gpu-usage
    >    in_use  usable  total  free
    >    18      34      55     16

    # Raw CSV output:
    $ ./gpu-usage -p
    >    in_use,usable,total,free
    >    18,34,55,16

    # Raw CSV, suppress header:
    $ ./gpu-usage -p -h
    >    18,34,55,16

    # Specify specific nodes in comma separated list:
    $ ./gpu-usage -n charles01,charles03
    >    in_use  usable  total  free
    >    1       2       4      1

    # Same as above but with summarised node format:
    $ ./gpu-usage -n charles[01,03]
    >    in_use  usable  total  free
    >    1       2       4      1

    # Example with split list:
    $ ./gpu-usage -n charles[01-06,11-19]
    >    in_use  usable  total  free
    >    14      26      47     12

EOM
}

while getopts 'n:hp' flag; do
  case "${flag}" in
    n) nodes="${OPTARG}" ;;
    h) header=false ;;
    p) pretty=false ;;
    *) print_usage
       exit ;;
  esac
done

if [ "$pretty" = true ]; then
  $0 -p -n ${nodes} | column -t -s','
  exit 0
fi

# Count number of GPUs requested by running jobs
USED=`squeue -t R -o %b -w ${nodes} | grep -o ':[0-9]' | awk ' {s+=substr($1,2)} END {print s}'`
if [ "$USED" == '' ]; then
  USED=0
fi

# Count number of GPUS in nodes marked idle or mix
USABLE=$(sinfo -t idle,mix,alloc -r -N -o %G -n ${nodes} | grep -o ':[0-9]' | awk ' {s+=substr($1,2)} END {print s}')
if [ "$USABLE" == '' ]; then
  USABLE=0
fi

# Count number of GPUs in all nodes
TOTAL=$(sinfo -N -o %G -n ${nodes} | grep -o ':[0-9]' | awk ' {s+=substr($1,2)} END {print s}')
if [ "$TOTAL" == '' ]; then
  TOTAL=0
fi

# Get number of free GPUs
FREE=$(expr "${USABLE}" - "${USED}")

if [ "$header" = true ]; then 
  echo "in_use,usable,total,free"
fi
echo "${USED},${USABLE},${TOTAL},${FREE}"